RyanDBarnett/adopt_dont_shop_paired

app/controllers/reviews_controller.rb, app/views/reviews/edit.html.erb, app/views/reviews/new.html.erb, app/views/shelters/show.html.erb, config/routes.rb, spec/features/reviews/edit_spec.rb, spec/features/reviews/new_spec.rb, spec/features/shelters/show_spec.rb, spec/models/review_spec.rb
- Add shelter reviews to shelter show page
- Add edit review link and path tests to shelter show spec
- Add edit review spec/test
- Add edit review form/view
- Add update and edit actions to reviews controller
- Change new review form path tests to go to /shelters/#{@shelter_1.id}/reviews/new
- Change new review form path from /shelter/#{@shelter.id} to /shelters/#{@shelter.id}/reviews
- Remove validate presence of image from review model test because it should be optional
Route Changes:
```
get '/shelters/:id/create_review', to: 'reviews#new'
post '/shelters/:id', to: 'reviews#create'
```
to
```
get '/shelters/:shelter_id/reviews/new', to: 'reviews#new'
post '/shelters/:id', to: 'reviews#create'	  post '/shelters/:shelter_id/reviews', to: 'reviews#create'
get …
```
=> I1 edit review2

app/controllers/reviews_controller.rb, spec/features/reviews/edit_spec.rb
Sad path / flash functionality with tests for incomplete review edit. Line comments in changed files.
=> I1 review edit sad path

.gitignore, app/controllers/reviews_controller.rb, app/views/shelters/show.html.erb, config/routes.rb, spec/features/reviews/edit_spec.rb, spec/features/shelters/show_spec.rb
Delete review functionality with tests. Leaving a few in-line comments.
=> I1 delete review

app/views/layouts/application.html.erb, spec/features/layout/application_spec.rb
Add fav indicator test and add indicator to application view.
=> I2 fav indicator

app/controllers/application_controller.rb, app/controllers/favorites_controller.rb, app/controllers/pets_controller.rb, app/poro/favorites.rb, app/views/layouts/application.html.erb, app/views/pets/show.html.erb, config/routes.rb, spec/features/pets/show_spec.rb, spec/models/favorites_spec.rb
Made favorite pets counter dynamic with tests.
=> I2 fav creation

app/controllers/favorites_controller.rb, app/views/favorites/index.html.erb, config/routes.rb, spec/features/favorites/index_spec.rb
- Add remove all favorite pets test
- Add favorites destroy route
- Add destroy action to favorites controller
- Add remove all favorite pets button to favorites index
=> I2 remove all favs

app/controllers/favorites_controller.rb, app/views/pets/show.html.erb, config/routes.rb, spec/features/pets/show_spec.rb
Add cant fav pet more than once tests
Add delete fav pet route
Update fav controller destroy action to handle both deleting one pet and all pets
Add remove from favorites button to pets show view
=> I2 no fav pet twice

app/controllers/application_controller.rb, app/controllers/applications_controller.rb, app/controllers/pets_applications_controller.rb, app/models/application.rb, app/models/pet.rb, app/models/pet_application.rb, db/migrate/20200829225507_create_applications.rb, db/migrate/20200829234421_create_pet_applications.rb, db/schema.rb, spec/models/application_spec.rb, spec/models/pet_application_spec.rb, spec/models/pet_spec.rb
Applications and pet_applications table migrations with models and tests.
=> I3 table migrations

app/controllers/applications_controller.rb, app/models/application.rb, app/views/applications/new.html.erb, app/views/favorites/index.html.erb, config/routes.rb, spec/features/applications/new_spec.rb
Add application functionality with tests, looks like there might be some merge conflicts.
=> I3 pet application new

Gemfile.lock, app/controllers/applications_controller.rb, app/models/application.rb, spec/features/applications/new_spec.rb
Sad path functionality for incomplete applications.
=> I3 incomplete application

app/controllers/applications_controller.rb, app/controllers/favorites_controller.rb, app/views/favorites/index.html.erb, spec/features/favorites/index_spec.rb
Add pet applications to join table
Add list of applied pets to favorites index
Add test for applied pet links on fav index
=> I3 list applied pets fav index

app/controllers/applications_controller.rb, app/views/applications/index.html.erb, app/views/pets/show.html.erb, config/routes.rb, spec/features/applications/index_spec.rb
Add application index view, action, tests. My commits got a bit messed up because I did not commit after fixing merge conflicts, sorry about that.
=> I3 application index

app/controllers/applications_controller.rb, app/views/applications/show.html.erb, app/views/pets/show.html.erb, config/routes.rb, db/migrate/20200831011306_change_pet_adoptable_to_status.rb, db/schema.rb, spec/features/applications/show_spec.rb, spec/features/pets/show_spec.rb
Add tests for approve application links
Add applications patch route
Add update action to applications controller
Add approve application link to application show view
**Schema Change:** Rename pet adoptable table column to status and give default of adoptable
Update pet show status test to reflect changes to pet status
Update pet show view to use status attribute instead of adoptable because of renaming
=> I3 approving application

spec/features/applications/show_spec.rb
Add test to verify user can approve multiple pets on an application
=> Add test for user approving any number of pets on application

app/controllers/applications_controller.rb, spec/features/applications/show_spec.rb
Add flash message for application approval button when pet already has approved application.
Add test.
=> I3 application sad path

app/controllers/applications_controller.rb, app/models/application.rb, spec/models/application_spec.rb
Adds new method to Application model, adds method to applications_controller, adds model test for new method.
=> I3 create with pets method

app/controllers/applications_controller.rb, app/models/application.rb, spec/models/application_spec.rb
Reverts RyanDBarnett/adopt_dont_shop_paired#66
=> Revert "I3 create with pets method"

app/controllers/applications_controller.rb, app/models/application.rb, spec/models/application_spec.rb
Reverts RyanDBarnett/adopt_dont_shop_paired#67
=> Revert "Revert "I3 create with pets method""

app/controllers/applications_controller.rb, app/views/applications/index.html.erb, app/views/applications/show.html.erb, config/routes.rb, spec/features/applications/index_spec.rb, spec/features/applications/show_spec.rb
Update application show to directly use application and not go through pet application join.
All tests passing except for skipped flash message
=> I3 refac show action

app/controllers/reviews_controller.rb, app/controllers/shelters_controller.rb, app/models/shelter.rb, spec/features/shelters/show_spec.rb, spec/models/shelter_spec.rb
Add delete shelter sad path:
Add to destroy method in shelters_controller,
Add test to shelters/show_spec,
Add methods to shelter model,
Add tests for shelter model methods.
=> I4 delete shelter sadpath

app/controllers/reviews_controller.rb, app/controllers/shelters_controller.rb, app/models/shelter.rb, spec/features/shelters/show_spec.rb, spec/models/shelter_spec.rb
Add test for deletion of shelter with pets that have no approved applications.
=> I4 shelter delete deletes pets

app/controllers/shelters_controller.rb, spec/features/shelters/edit_spec.rb, spec/features/shelters/new_spec.rb
Add sad path tests for incomplete shelter create and edit forms.
Add sad path conditionals and flash messages to controller actions.
=> I4 shelters incomplete forms sadpaths

app/models/shelter.rb, app/views/shelters/show.html.erb, spec/features/shelters/show_spec.rb, spec/models/shelter_spec.rb
This probably should have been split into 3 smaller user stories but oh well.
Create feature and model tests for the following:
count of pets that are at that shelter
average shelter review rating
number of applications on file for that shelter
=> I4 shelter statistics

app/controllers/pets_controller.rb, spec/features/pets/index_spec.rb
Sad path for delete pet with approved application.
=> I5 delete pet sad path

app/controllers/pets_controller.rb, app/views/pets/edit.html.erb, spec/features/pets/edit_spec.rb, spec/features/pets/new_spec.rb
Added flash messages for incomplete pet new or edit form. 
I tried to make the message tell the user which specific fields they need to fill out but its ugly. Any ideas on refactoring is appreciated.
=> I5 pet flash message

app/controllers/pets_controller.rb, spec/features/pets/index_spec.rb
Adds favorite removal when deleting pet test,
Adds favorite removal functionality to pet destroy action
=> I5 favorite removal

app/views/pets/index.html.erb, app/views/reviews/new.html.erb, app/views/shelterpets/index.html.erb, app/views/shelters/show.html.erb, spec/features/pets/index_spec.rb, spec/features/reviews/new_spec.rb, spec/features/shelters/show_spec.rb
Add tests for shelter names as links,
Edit views making all shelter names links
=> I5 shelter names as links

app/views/applications/show.html.erb, spec/features/applications/show_spec.rb
"Add test for applicant name as link"
"Edit applicant name to be link"
=> I6 applicant names as links

app/controllers/applications_controller.rb, app/views/applications/show.html.erb, app/views/favorites/index.html.erb, db/migrate/20200902222721_add_approved_app_to_pets.rb, db/schema.rb, spec/features/applications/show_spec.rb
Add migration for approved_apps to pets
Add automatic update functionality for new column to update action in pets controller
Add conditional to application show view to take new column into account which determines if approve/revoke link is applied
Add header to favorites view to differentiate between favorited pets and pets that have been applied for
=> Application links refactor
